# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('dispenser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddata',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='doctor.Medicine'),
        ),
        migrations.AddField(
            model_name='load',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='dispenser.Device'),
        ),
    ]
