# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('dispenser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenselog',
            name='medicine',
            field=models.ManyToManyField(related_name='dispenses', to='doctor.Medicine'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='doctor.Prescription'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='dispenser.Device'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='doctor.Medicine'),
        ),
    ]
