# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0002_auto_20180321_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispenselog',
            name='prescription',
        ),
    ]
