# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-05 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
        ('dispenser', '0002_auto_20180605_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_loads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='actual_composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_dispenses', to='doctor.Composition'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='dispenser.Chamber'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='load_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='dispenser.LoadData'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='medicine',
            field=models.ManyToManyField(related_name='dispenses', to='doctor.Medicine'),
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='doctor.Prescription'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambers', to='dispenser.Device'),
        ),
    ]
