# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0004_medicine_name'),
        ('dispenser', '0003_remove_dispenselog_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='dispenser.Device')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_loads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chamber',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='chamber',
            name='chamber_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaddata',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='dispenser.Chamber'),
        ),
        migrations.AddField(
            model_name='loaddata',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_data', to='dispenser.Load'),
        ),
        migrations.AddField(
            model_name='loaddata',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='doctor.Medicine'),
        ),
    ]
