# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_medicine_name'),
        ('dispenser', '0004_auto_20180422_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenselog',
            name='prescription',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='doctor.Prescription'),
            preserve_default=False,
        ),
    ]
