# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-09 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180605_1841'),
        ('dispenser', '0005_device_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='medicine',
        ),
        migrations.AddField(
            model_name='dispenselog',
            name='medicine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='doctor.Medicine'),
            preserve_default=False,
        ),
    ]
