# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0005_dispenselog_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenselog',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='dispenser.Device'),
            preserve_default=False,
        ),
    ]
