# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0006_dispenselog_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddata',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
