# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
