# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
