# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180616_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='refund_details',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='walletbalance',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='walletbalance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_hash',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='long_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='short_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sms_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_board_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='LineItems',
        ),
        migrations.DeleteModel(
            name='Refund_details',
        ),
        migrations.DeleteModel(
            name='WalletBalance',
        ),
    ]
