# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180619_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
