# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
