# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180319_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_note',
            field=models.TextField(blank=True, help_text='Doctor Note', null=True),
        ),
    ]
