# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20180321_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
