# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_schedule_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
