# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_medicine_otc'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
