# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
